### ISSUE TITLE
Examples won't run?

### ISSUE THREAD

**Issue by aspannaus** [AdrienCorenflos/parallel-ps#1]
Hey there, 

Thanks for putting together the library, I'm interested in using it for some of my work. In starting to oriented to the code, I'm having an issue getting the examples to successfully run. Below is the error message I'm getting from the`cox.py` and `theta_logistic.py`scripts (I didn't try any others).

```  
File "/Github/parallel-ps/examples/standard/cox.py", line 17, in <module>
    from parallel_ps.parallel_smoother import smoothing

  File "/Github/parallel-ps/parallel_ps/parallel_smoother.py", line 35, in <module>
    from parallel_ps.operators import operator, lazy_operator

  File "/Github/parallel-ps/parallel_ps/operators.py", line 95, in <module>
    @partial(jax.jit, static_argnums=(2, 3, 4, 5, 6), donate_argnums=(0, 1))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/api.py", line 281, in jit
    return pjit.make_jit(
           ^^^^^^^^^^^^^^

  File "/miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 529, in make_jit
    jit_info = _parse_jit_arguments(
               ^^^^^^^^^^^^^^^^^^^^^

  File "/miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/pjit.py", line 447, in _parse_jit_arguments
    donate_argnums, donate_argnames, static_argnums, static_argnames = resolve_argnums(
                                                                       ^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/api_util.py", line 540, in resolve_argnums
    _validate_argnums(signature, static_argnums, "static_argnums")

  File "miniconda3/envs/jax/lib/python3.11/site-packages/jax/_src/api_util.py", line 170, in _validate_argnums
    raise ValueError(f"Jitted function has {argnums_name}={argnums}, "

ValueError: Jitted function has static_argnums=(2, 3, 4, 5, 6), but only accepts 4 positional arguments
``` 

Here are the versions of the library imports I'm using:
- jax - '0.4.30'
- numpy - '2.0.0'
- numba - '0.60.0'
- tensorflow_probability  - '0.25.0-dev20240809'

Thanks in advance for any insight you can provide.

**Comment by AdrienCorenflos** [comment]
Hi,

Thanks for reporting! Best guess is that JAX used to be less strict about superfluous argnums (and I hadn't been super precise visibly). 
JAX GPU compatibility was also a bit fiddly so I hadn't frozen the version then. 

Either way, fix was easy -> change to static_argnums=(2, 3), I've also fixed other bugs (for exactly the same reason) I could find and (most) unittests run (I'm on the laptop so can't run it all/check the examples, but it's usually a good sign!)

Additionally, https://github.com/EEA-sensors/parallel-non-linear-gaussian-smoothers was also stale, so I fixed it too -> you should upgrade the dependency to v1.1.2.

Let me know if you run into more issues!

**Comment by AdrienCorenflos** [comment]
On a side note, a lot of the methods in here are also supported by https://github.com/AdrienCorenflos/aux-ssm-samplers/tree/main which has other perks (in terms of dimensional scalability etc) and IMO is a bit cleaner in terms of coding.

**Comment by aspannaus** [comment]
Great, thanks for updating the library and pointing me to your other repo. I'll check it out and give it a try. Thanks again!
